# Generated by Django 6.0.2 on 2026-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Fresh', max_length=20),
        ),
    ]
